### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by Perlence** [pocke/lemonade#15]
Should lemonade convert line endings? For example if you copy something on Windows host and `lemonade paste` it on Linux host, there are `\r` characters that are almost never needed.

**Comment by pocke** [comment]
It's a nice idea.
However, I don't think lemonade should convert it as default. When copy a binary file, lemonade may malfunction.

I'll add a option for converting line ending.


example
------



`lemonade.toml` for lemonade server. https://github.com/pocke/lemonade#server

```toml
port = 1234
allow = '192.168.0.0/24'
convert_eol = true
```
